const DEFAULT_PENS={
  mjr5:{brand:'Mounjaro',abbr:'MJR',strength:'5 mg',totalMg:20,totalClicks:240,mappings:{'2.5':30,'5':60}},
  mjr10:{brand:'Mounjaro',abbr:'MJR',strength:'10 mg',totalMg:40,totalClicks:240,mappings:{'2.5':15,'5':30,'7.5':45,'10':60}},
  mjr125:{brand:'Mounjaro',abbr:'MJR',strength:'12.5 mg',totalMg:50,totalClicks:240,mappings:{'2.5':12,'5':24,'7.5':36,'10':48,'12.5':60}},
  mjr15:{brand:'Mounjaro',abbr:'MJR',strength:'15 mg',totalMg:60,totalClicks:240,mappings:{'2.5':10,'5':20,'7.5':30,'10':40,'12.5':50,'15':60}},
  wgv1:{brand:'Wegovy',abbr:'WGV',strength:'1 mg',totalMg:4,totalClicks:300,mappings:{'0.25':19,'0.5':37,'1':75}},
  wgv24:{brand:'Wegovy',abbr:'WGV',strength:'2.4 mg',totalMg:9.6,totalClicks:300,mappings:{'0.25':8,'0.5':16,'1':31,'1.7':51,'2.4':75}}
};
const CLICK_PATHS={
  mjr5:{standard:[30,60],half:[15,30,45,60]},
  mjr10:{standard:[15,30,45,60],half:[8,15,23,30,38,45,53,60]},
  mjr125:{standard:[12,24,36,48,60],half:[6,12,18,24,30,36,42,48,54,60]},
  mjr15:{standard:[10,20,30,40,50,60],half:[5,10,15,20,25,30,35,40,45,50,55,60]},
  wgv1:{standard:[19,37,75],half:[9,19,28,37,56,75]},
  wgv24:{standard:[8,16,31,51,75],half:[8,16,24,31,40,51,60,68,75]}
};
const INJECTORS=['หมอฉีดให้','ฉีดเอง','ผู้ดูแลฉีดให้'];
const MILESTONES=['','นัดพบแพทย์','นัดวัด InBody','ติดตามอาการ'];
const SAVED_PENS=load('glp1-pens',{});
let pens=clone(DEFAULT_PENS),rows=load('glp1-plan',[]),crmRows=load('glp1-crm',[]),planConfig=load('glp1-config',null),planMeta=null;
Object.entries(SAVED_PENS).forEach(([key,value])=>{pens[key]={...(pens[key]||{}),...value}});
const $=s=>document.querySelector(s),body=$('#planBody');
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||clone(f)}catch{return clone(f)}}
function fmt(v,digits=3){return v===''?'':Number(v).toLocaleString('en-US',{maximumFractionDigits:digits,useGrouping:false})}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDays(s,n){const [y,m,d]=s.split('-').map(Number);return iso(new Date(y,m-1,d+n))}
function thaiDate(s){if(!s)return '';const [y,m,d]=s.split('-');return `${d}/${m}/${y}`}
function shortThaiDate(s){if(!s)return '';const [y,m,d]=s.split('-');return `${d}/${m}/${String(y).slice(-2)}`}
function parseStartDate(value){const v=String(value||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const match=v.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2}|\d{4})$/);if(!match)return '';let year=Number(match[3]);if(year<100)year+=2000;const month=Number(match[2]),day=Number(match[1]),date=new Date(year,month-1,day);if(date.getFullYear()!==year||date.getMonth()!==month-1||date.getDate()!==day)return '';return iso(date)}
function displayPen(key){const p=pens[key];return `${p.abbr} ${p.strength} (${fmt(p.totalMg)}mg/ด้าม)`}
function optionList(items,value){return items.map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}
function penOptions(value){return Object.keys(pens).map(k=>`<option value="${k}" ${k===value?'selected':''}>${displayPen(k)}</option>`).join('')}
function mappedClicks(pen,dose){return pens[pen]?.mappings[String(Number(dose))]}
function exactDoseForClicks(pen,clicks){const found=Object.entries(pens[pen]?.mappings||{}).find(([,c])=>Number(c)===Number(clicks));return found?Number(found[0]):undefined}
function doseForClicks(pen,clicks){const exact=exactDoseForClicks(pen,clicks);if(exact!==undefined)return exact;const entries=Object.entries(pens[pen].mappings).map(([d,c])=>[Number(d),Number(c)]).sort((a,b)=>b[1]-a[1]);return Number((Number(clicks)*(entries[0][0]/entries[0][1])).toFixed(2))}
function derivedCapacity(pen){const p=pens[pen];if(Number(p.totalClicks)>0)return Number(p.totalClicks);const entries=Object.entries(p.mappings).map(([d,c])=>[Number(d),Number(c)]).sort((a,b)=>b[0]-a[0]);return Math.round(p.totalMg/(entries[0][0]/entries[0][1]))}
function clickPath(){const pen=$('#basePen').value,mode=$('#dosePath').value;return CLICK_PATHS[pen]?.[mode]||Object.values(pens[pen].mappings).map(Number).sort((a,b)=>a-b)}
function mismatch(r){const expected=mappedClicks(r.pen,r.dose);return r.dose!==''&&r.clicks!==''&&(expected===undefined||Number(r.clicks)!==Number(expected))}
function mappingWarning(r){const exact=exactDoseForClicks(r.pen,r.clicks);return exact===undefined?'half-step / custom':Number(r.dose)!==exact?`mapping ${fmt(exact)} mg`:'ตรงตาม mapping'}
function renderPens(reset=true){const brand=$('#baseDrug').value,selected=$('#basePen').value,keys=Object.keys(pens).filter(k=>pens[k].brand===brand);$('#basePen').innerHTML=keys.map(k=>`<option value="${k}" ${k===selected?'selected':''}>${displayPen(k)}</option>`).join('');if(!keys.includes($('#basePen').value))$('#basePen').value=keys[0];renderStartOptions(reset)}
function renderStartOptions(reset=true){const path=clickPath(),current=Number($('#startClicks').value);$('#startClicks').innerHTML=path.map(c=>{const dose=doseForClicks($('#basePen').value,c),custom=exactDoseForClicks($('#basePen').value,c)===undefined?' · half-step':'';return `<option value="${c}" ${!reset&&c===current?'selected':''}>${fmt(dose)} mg · ${c} click${custom}</option>`}).join('');if(reset||!path.includes(current))$('#startClicks').value=path[0];syncStartDose();updateRulePreview()}
function syncStartDose(){const c=Number($('#startClicks').value);$('#startDose').value=fmt(doseForClicks($('#basePen').value,c))}
function updateRulePreview(){const path=clickPath(),start=Number($('#startClicks').value),idx=Math.max(0,path.indexOf(start));if(!$('#autoStep').checked){$('#rulePreview').textContent=`คงที่ ${start} click จนยาไม่พอ`;return}const direction=$('#doseDirection').value,sequence=direction==='down'?path.slice(0,idx+1).reverse():path.slice(idx);$('#rulePreview').textContent=(direction==='down'?'ถอยยา: ':'เพิ่มยา: ')+sequence.join(' → ')+' click'}
function newRow(date,pen,dose,clicks){return {date,pen,dose,clicks,injector:$('#defaultInjector').value||'ฉีดเอง',weight:'',milestone:'',note:''}}
function plannedClickAt(index){if(!planConfig)return Number(rows.at(-1)?.clicks||0);const startIndex=Math.max(0,planConfig.path.indexOf(Number(planConfig.startClicks)));if(!planConfig.autoStep)return Number(planConfig.startClicks);const offset=Math.floor(index/planConfig.every),target=planConfig.direction==='down'?Math.max(0,startIndex-offset):Math.min(planConfig.path.length-1,startIndex+offset);return planConfig.path[target]}
function generate(){const start=parseStartDate($('#startDate').value),pen=$('#basePen').value,path=clickPath(),startClicks=Number($('#startClicks').value),every=Math.max(1,Number($('#stepEvery').value)||4),startIndex=path.indexOf(startClicks),startNumber=Math.max(1,Number($('#startNumber').value)||1),intervalDays=[7,10].includes(Number($('#intervalDays').value))?Number($('#intervalDays').value):7;if(!start||startIndex<0)return toast('กรุณากรอกวันแบบ dd/mm/yyyy และเลือกโดสเริ่มต้น');$('#startDate').value=thaiDate(start);$('#startDateNative').value=start;$('#startNumber').value=startNumber;planConfig={start,pen,mode:$('#dosePath').value,path:[...path],startClicks,every,startNumber,intervalDays,direction:$('#doseDirection').value,autoStep:$('#autoStep').checked,injector:$('#defaultInjector').value};localStorage.setItem('glp1-config',JSON.stringify(planConfig));rows=[];rebalanceRows();buildCrm(true);const duration=rows.length>1?(rows.length-1)*intervalDays:0;toast(`คำนวณได้ ${rows.length} ครั้ง ครอบคลุม ${duration} วัน`)}
function rebalanceRows(){if(!planConfig&&!rows.length)return;const pen=planConfig?.pen||rows[0].pen,capacity=derivedCapacity(pen),intervalDays=Number(planConfig?.intervalDays)||7;let used=0,keep=[];for(const r of rows){const clicks=Number(r.clicks||0);if(r.pen!==pen||clicks<=0||used+clicks>capacity)break;keep.push(r);used+=clicks}rows=keep;while(rows.length<60){const clicks=plannedClickAt(rows.length);if(!clicks||used+clicks>capacity)break;const date=rows.length?addDays(rows.at(-1).date,intervalDays):planConfig.start;const r=newRow(date,pen,doseForClicks(pen,clicks),clicks);if(planConfig?.injector)r.injector=planConfig.injector;rows.push(r);used+=clicks}planMeta={pen,capacity,used,remaining:capacity-used,nextClicks:plannedClickAt(rows.length)};save();render()}
function calculateMeta(){if(!rows.length){planMeta=null;return}const pen=rows[0].pen,capacity=derivedCapacity(pen),used=rows.filter(r=>r.pen===pen).reduce((s,r)=>s+Number(r.clicks||0),0);planMeta={pen,capacity,used,remaining:Math.max(0,capacity-used),nextClicks:plannedClickAt(rows.length)||Number(rows.at(-1).clicks||0),mixed:rows.some(r=>r.pen!==pen)}}
function render(){const startNumber=Math.max(1,Number(planConfig?.startNumber)||1);body.innerHTML=rows.map((r,i)=>{const injectionNumber=startNumber+i;return `<tr data-i="${i}" class="${mismatch(r)?'mismatch ':''}${i&&rows[i-1].pen!==r.pen?'changed-row':''}"><td><div class="week-cell"><span class="week-num">${String(injectionNumber).padStart(2,'0')}</span><div class="date-picker row-date"><input data-f="dateDisplay" type="text" inputmode="numeric" value="${thaiDate(r.date)}" placeholder="dd/mm/yyyy" maxlength="10"><button type="button" class="calendar-btn" data-act="calendar" aria-label="เปิดปฏิทินครั้งที่ ${injectionNumber}">▦</button><input data-f="dateNative" type="date" class="native-calendar" value="${r.date||''}" tabindex="-1" aria-hidden="true"></div></div></td><td><select data-f="pen" class="pen-select">${penOptions(r.pen)}</select></td><td><input data-f="dose" class="dose-input calculated" type="number" value="${r.dose}" readonly title="คำนวณอัตโนมัติจากจำนวนคลิก"></td><td><div class="click-wrap"><input data-f="clicks" type="number" min="1" step="1" value="${r.clicks}"><span class="row-warning">${mappingWarning(r)}</span></div></td><td><select data-f="injector">${optionList(INJECTORS,r.injector)}</select></td><td><input data-f="weight" class="weight-input" type="number" min="0" step="0.1" placeholder="kg" value="${r.weight}"></td><td><select data-f="milestone" class="milestone-select">${optionList(MILESTONES,r.milestone)}</select></td><td><input data-f="note" class="note-input" placeholder="เพิ่มหมายเหตุ" value="${esc(r.note)}"></td><td><div class="row-actions"><button class="row-btn" data-act="copy" title="คัดลอกแถวก่อนหน้า">↙</button><button class="row-btn" data-act="fill4" title="ใช้ค่านี้กับ 4 ครั้งถัดไป">+4</button></div></td></tr>`}).join('');if(rows.length&&!planMeta)calculateMeta();updateOutput();updateSummary()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function updateSummary(){if(!planMeta){$('#penSummary').innerHTML='<p>เลือกการตั้งค่าด้านบน แล้วกด “คำนวณแผนทั้งด้าม”</p>';$('#trackerSummary').textContent='ยังไม่ได้คำนวณ';return}const p=pens[planMeta.pen],usedMg=p.totalMg*(planMeta.used/planMeta.capacity),remainingMg=p.totalMg*(planMeta.remaining/planMeta.capacity),interval=Number(planConfig?.intervalDays)||7,duration=rows.length>1?(rows.length-1)*interval:0;$('#penSummary').innerHTML=`<div><small>ยาทั้งด้าม</small><strong>${fmt(p.totalMg)} mg</strong><span>${planMeta.capacity} click</span></div><div><small>ฉีดได้ตามแผน</small><strong>${rows.length} ครั้ง</strong><span>ทุก ${interval} วัน · ${duration} วัน</span></div><div><small>ใช้ไป</small><strong>${planMeta.used} click</strong><span>≈ ${fmt(usedMg,2)} mg</span></div><div class="${planMeta.remaining?'remaining':''}"><small>คงเหลือ</small><strong>${planMeta.remaining} click</strong><span>≈ ${fmt(remainingMg,2)} mg</span></div>`;if(planMeta.mixed)$('#trackerSummary').textContent='มีการเปลี่ยนชนิดปากกาในตาราง กรุณาคำนวณยอดแยกด้าม';else if(planMeta.remaining===0)$('#trackerSummary').textContent='ใช้ครบตามความจุที่ตั้งไว้';else $('#trackerSummary').textContent=`เหลือ ${planMeta.remaining} click (≈ ${fmt(remainingMg,2)} mg) ไม่พอสำหรับโดสถัดไป ${planMeta.nextClicks} click — ให้แพทย์กำหนดการใช้`}
function updateOutput(){if(!rows.length){$('#patientText').textContent='ยังไม่มีแผน — เลือกปากกา รูปแบบปรับโดส และวันเริ่มต้น';return}const header=`Plan: ${displayPen(rows[0].pen)}`,startNumber=Math.max(1,Number(planConfig?.startNumber)||1),interval=Number(planConfig?.intervalDays)||7,duration=rows.length>1?(rows.length-1)*interval:0;const lines=rows.map((r,i)=>{let line=`-ครั้งที่ ${startNumber+i} ${thaiDate(r.date)} ${displayPen(r.pen)} ${r.injector} ${fmt(r.dose)} mg คือ ${r.clicks} click`;if(r.weight!=='')line+=r.injector==='หมอฉีดให้'?` BW ที่ clinic ${fmt(r.weight)} kg`:` BW ${fmt(r.weight)} kg`;if(r.milestone)line+=` ${r.milestone}`;if(r.note)line+=` ${r.note}`;return line});let footer=`รวม ${rows.length} ครั้ง (ทุก ${interval} วัน · ระยะเวลา ${duration} วัน)`;if(planMeta?.remaining>0)footer+=`\nคงเหลือ ${planMeta.remaining} click — ไม่พอสำหรับโดสถัดไป ${planMeta.nextClicks} click`;$('#patientText').textContent=[header,...lines,'',footer].join('\n')}
function save(){localStorage.setItem('glp1-plan',JSON.stringify(rows));$('#saveState').textContent='บันทึกในเครื่องแล้ว'}
body.addEventListener('input',e=>{const tr=e.target.closest('tr'),f=e.target.dataset.f;if(!tr||!f)return;const r=rows[+tr.dataset.i];if(f==='dateDisplay'){const parsed=parseStartDate(e.target.value);if(parsed){r.date=parsed;tr.querySelector('[data-f="dateNative"]').value=parsed;save();updateOutput()}return}if(f==='dateNative'){r.date=e.target.value;tr.querySelector('[data-f="dateDisplay"]').value=thaiDate(r.date);save();updateOutput();return}r[f]=e.target.value;if(f==='pen'){const mc=mappedClicks(r.pen,r.dose);if(mc!==undefined)r.clicks=mc;planMeta=null;save();render();return}if(f==='dose'){const mc=mappedClicks(r.pen,r.dose);if(mc!==undefined){r.clicks=mc;tr.querySelector('[data-f="clicks"]').value=mc}}if(f==='clicks'){r.dose=doseForClicks(r.pen,r.clicks);tr.querySelector('[data-f="dose"]').value=fmt(r.dose)}tr.classList.toggle('mismatch',mismatch(r));tr.querySelector('.row-warning').textContent=mappingWarning(r);planMeta=null;calculateMeta();save();updateOutput();updateSummary()});
body.addEventListener('change',e=>{const f=e.target.dataset.f;if(f==='clicks'){rebalanceRows();toast(`ปรับโดสและแผนทั้งด้ามแล้ว เหลือ ${planMeta.remaining} click`);return}if(f==='dateDisplay'){const tr=e.target.closest('tr'),r=rows[+tr.dataset.i],parsed=parseStartDate(e.target.value);if(parsed){r.date=parsed;e.target.value=thaiDate(parsed);tr.querySelector('[data-f="dateNative"]').value=parsed;save();updateOutput()}else e.target.value=thaiDate(r.date)}});
body.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b)return;e.preventDefault();if(b.dataset.act==='calendar'){const native=b.parentElement.querySelector('[data-f="dateNative"]');if(native.showPicker)native.showPicker();else native.click();return}const i=+b.closest('tr').dataset.i;if(b.dataset.act==='copy'&&i>0){const date=rows[i].date;rows[i]={...clone(rows[i-1]),date}}else if(b.dataset.act==='fill4'){for(let x=i+1;x<Math.min(rows.length,i+5);x++){const date=rows[x].date;rows[x]={...clone(rows[i]),date}}}planMeta=null;save();render();toast(b.dataset.act==='copy'?'คัดลอกแถวก่อนหน้าแล้ว':'เติม 4 ครั้งถัดไปแล้ว')});
function crmOffsets(){return [...new Set($('#crmOffsets').value.split(',').map(x=>Number(x.trim())).filter(x=>Number.isInteger(x)&&x>=0))].sort((a,b)=>a-b)}
function buildCrm(){const start=parseStartDate($('#startDate').value);if(!start){crmRows=[];renderCrm();return}crmRows=crmOffsets().map(day=>({day,date:addDays(start,day)}));localStorage.setItem('glp1-crm',JSON.stringify(crmRows));localStorage.setItem('glp1-crm-offsets',$('#crmOffsets').value);renderCrm()}
function renderCrm(){if(!crmRows.length){$('#crmList').innerHTML='<p class="empty">ยังไม่มีวันติดตาม กรุณาเลือกวันฉีดครั้งแรก</p>';$('#crmText').textContent='';return}$('#crmList').innerHTML=crmRows.map((r,i)=>`<div class="crm-item crm-simple" data-crm="${i}"><span class="day-pill">D${r.day}</span><label>วันที่ติดตาม<div class="date-picker crm-date"><input data-c="dateDisplay" type="text" inputmode="numeric" value="${thaiDate(r.date)}" placeholder="dd/mm/yyyy" maxlength="10"><button type="button" class="calendar-btn" data-crm-act="calendar" aria-label="เปิดปฏิทิน D${r.day}">▦</button><input data-c="dateNative" type="date" class="native-calendar" value="${r.date||''}" tabindex="-1" aria-hidden="true"></div></label></div>`).join('');updateCrmText()}
function updateCrmText(){if(crmRows.length)$('#crmText').textContent=['CRM Follow-up · 3 เดือน',...crmRows.map(r=>`-D${r.day} ${thaiDate(r.date)}`)].join('\n')}
function saveCrm(){localStorage.setItem('glp1-crm',JSON.stringify(crmRows));updateCrmText()}
$('#crmList').addEventListener('input',e=>{const item=e.target.closest('[data-crm]'),field=e.target.dataset.c;if(!item||!field)return;const r=crmRows[+item.dataset.crm];if(field==='dateDisplay'){const parsed=parseStartDate(e.target.value);if(parsed){r.date=parsed;item.querySelector('[data-c="dateNative"]').value=parsed;saveCrm()}return}if(field==='dateNative'&&e.target.value){r.date=e.target.value;item.querySelector('[data-c="dateDisplay"]').value=thaiDate(r.date);saveCrm()}});
$('#crmList').addEventListener('change',e=>{if(e.target.dataset.c!=='dateDisplay')return;const item=e.target.closest('[data-crm]'),r=crmRows[+item.dataset.crm],parsed=parseStartDate(e.target.value);if(parsed){r.date=parsed;e.target.value=thaiDate(parsed);item.querySelector('[data-c="dateNative"]').value=parsed;saveCrm()}else e.target.value=thaiDate(r.date)});
$('#crmList').addEventListener('click',e=>{const b=e.target.closest('[data-crm-act="calendar"]');if(!b)return;e.preventDefault();const native=b.parentElement.querySelector('[data-c="dateNative"]');if(native.showPicker)native.showPicker();else native.click()});
$('#updateCrmBtn').onclick=()=>{buildCrm(false);toast('อัปเดตวันติดตามแล้ว')};
$('#copyCrmBtn').onclick=async()=>{if(!crmRows.length)return toast('ยังไม่มีตารางติดตาม');try{await navigator.clipboard.writeText($('#crmText').textContent);toast('คัดลอกตารางติดตามแล้ว')}catch{toast('คัดลอกไม่สำเร็จ')}};
async function copyPlan(){if(!rows.length)return toast('ยังไม่มีแผนให้คัดลอก');if(rows.some(mismatch)&&!confirm('มีค่า half-step/custom protocol ต้องการคัดลอกตามค่าที่แพทย์ตรวจแล้วใช่หรือไม่?'))return;try{await navigator.clipboard.writeText($('#patientText').textContent);toast('คัดลอกแผนแล้ว')}catch{toast('คัดลอกไม่สำเร็จ กรุณาเลือกข้อความด้วยตนเอง')}}
$('#copyBtn').onclick=copyPlan;$('#copyTopBtn').onclick=copyPlan;$('#printBtn').onclick=()=>{if(rows.some(mismatch)&&!confirm('มีค่า half-step/custom protocol ต้องการพิมพ์ต่อหรือไม่?'))return;window.print()};
function resetAllData(){if(!confirm('ล้างข้อมูลแผนการฉีดและ CRM ทั้งหมด? การตั้งค่าปากกาของคลินิกจะยังคงอยู่'))return;rows=[];crmRows=[];planConfig=null;planMeta=null;['glp1-plan','glp1-crm','glp1-config','glp1-crm-offsets'].forEach(k=>localStorage.removeItem(k));const today=iso(new Date());$('#startDate').value=thaiDate(today);$('#startDateNative').value=today;$('#baseDrug').value='Mounjaro';renderPens(true);$('#basePen').value='mjr10';$('#dosePath').value='half';renderStartOptions(true);$('#startNumber').value=1;$('#intervalDays').value='7';$('#doseDirection').value='up';$('#defaultInjector').value='ฉีดเอง';$('#autoStep').checked=true;$('#stepEvery').value=4;$('#crmOffsets').value='1, 13, 27, 41, 55, 69, 83';updateRulePreview();render();renderCrm();$('#saveState').textContent='ล้างข้อมูลแล้ว';toast('ล้างข้อมูลแผนและ CRM แล้ว')}
$('#generateBtn').onclick=generate;$('#baseDrug').onchange=()=>renderPens(true);$('#basePen').onchange=()=>renderStartOptions(true);$('#dosePath').onchange=()=>renderStartOptions(true);$('#startClicks').onchange=()=>{syncStartDose();updateRulePreview()};$('#doseDirection').onchange=updateRulePreview;$('#autoStep').onchange=updateRulePreview;$('#stepEvery').oninput=updateRulePreview;$('#resetBtn').onclick=resetAllData;
$('#startCalendarBtn').onclick=()=>{const native=$('#startDateNative');if(native.showPicker)native.showPicker();else native.click()};
$('#startDateNative').onchange=()=>{if($('#startDateNative').value)$('#startDate').value=thaiDate($('#startDateNative').value)};
$('#startDate').onblur=()=>{const parsed=parseStartDate($('#startDate').value);if(parsed){$('#startDate').value=thaiDate(parsed);$('#startDateNative').value=parsed}};
function settingsHtml(){return Object.entries(pens).map(([k,p])=>`<div class="setting-pen" data-pen="${k}"><h3>${p.brand} ${p.strength}</h3><div class="setting-grid"><label>ชื่อย่อ<input data-s="abbr" value="${esc(p.abbr)}"></label><label>Usable clicks/ด้าม<input data-s="totalClicks" type="number" min="1" value="${derivedCapacity(k)}"></label><label class="mapping-edit">Dose=click, คั่นด้วย comma<input data-s="mappings" value="${Object.entries(p.mappings).map(([d,c])=>`${d}=${c}`).join(', ')}"></label></div></div>`).join('')}
$('#settingsBtn').onclick=()=>{$('#settingsPens').innerHTML=settingsHtml();$('#settingsDialog').showModal()};
$('#saveSettingsBtn').onclick=e=>{e.preventDefault();document.querySelectorAll('.setting-pen').forEach(el=>{const p=pens[el.dataset.pen];p.abbr=el.querySelector('[data-s=abbr]').value.trim()||p.abbr;p.totalClicks=el.querySelector('[data-s=totalClicks]').value;const map={};el.querySelector('[data-s=mappings]').value.split(',').forEach(pair=>{const [d,c]=pair.split('=').map(x=>x.trim());if(d!==''&&c!==''&&!isNaN(d)&&!isNaN(c))map[String(Number(d))]=Number(c)});p.mappings=map});localStorage.setItem('glp1-pens',JSON.stringify(pens));$('#settingsDialog').close();renderPens(true);planMeta=null;render();toast('บันทึกการตั้งค่าคลินิกแล้ว')};
$('#restoreSettingsBtn').onclick=()=>{if(confirm('คืนค่าตาราง clinic protocol เริ่มต้น?')){$('#settingsPens').innerHTML=settingsHtml(pens=clone(DEFAULT_PENS))}};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2400)}
$('#crmOffsets').value=localStorage.getItem('glp1-crm-offsets')||'1, 13, 27, 41, 55, 69, 83';$('#dosePath').value=planConfig?.mode||'half';$('#stepEvery').value=planConfig?.every||4;$('#startNumber').value=Math.max(1,Number(planConfig?.startNumber)||1);$('#intervalDays').value=String(planConfig?.intervalDays||7);$('#doseDirection').value=planConfig?.direction||'up';$('#autoStep').checked=planConfig?.autoStep!==false;if(planConfig?.injector)$('#defaultInjector').value=planConfig.injector;
if(rows.length&&pens[rows[0].pen]){const pen=planConfig?.pen||rows[0].pen,start=planConfig?.start||rows[0].date;$('#startDate').value=thaiDate(start);$('#startDateNative').value=start;$('#baseDrug').value=pens[pen].brand;renderPens(true);$('#basePen').value=pen;renderStartOptions(true);const startClicks=Number(planConfig?.startClicks||rows[0].clicks);if(clickPath().includes(startClicks))$('#startClicks').value=startClicks;syncStartDose();updateRulePreview();if(!planConfig){planConfig={start:rows[0].date,pen,mode:$('#dosePath').value,path:[...clickPath()],startClicks:Number(rows[0].clicks),every:Number($('#stepEvery').value),startNumber:1,intervalDays:7,direction:'up',autoStep:$('#autoStep').checked,injector:rows[0].injector};localStorage.setItem('glp1-config',JSON.stringify(planConfig))}calculateMeta()}else{const today=iso(new Date());$('#startDate').value=thaiDate(today);$('#startDateNative').value=today;$('#baseDrug').value='Mounjaro';renderPens(true);$('#basePen').value='mjr10';renderStartOptions(true)}
render();if(crmRows.length)renderCrm();else buildCrm(false);
